sudo: required
services: 
  - docker

before_install:
  - docker build -t mahagney/react-test -f ./client/Dockerfile.dev .

script:
  - docker run mahagney/react-test npm test -- --coverage

after_success:
  - docker build -t mahagney/multi-client ./client
  - docker build -t mahagney/multi-nginx ./nginx
  - docker build -t mahagney/multi-server ./server
  - docker build -t mahagney/multi-worker ./worker